services:
    next-frontend:
        build:
            context: .
            dockerfile: dev/Dockerfile
        container_name: node-dev
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        entrypoint: ["tail", "-f", "/dev/null"]
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "api.torneig.local:host-gateway"
        networks:
            - proxy
networks:
    proxy:
        external: true
