version: '3.8'

services:
  node:
    image: node:24
    container_name: node-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    entrypoint: ["tail", "-f", "/dev/null"]
